### ISSUE TITLE
Rendering page language

### ISSUE THREAD

**Issue by puradawid** [puradawid/company-overflow#2]
Which language will be used in app?
- [HAML](http://haml.info/)
- [HTML.ERB](http://guides.rubyonrails.org/layouts_and_rendering.html)
- other?

The point is to build app **quickly and easy** but we need technology that will be understanable by all of us. @mateuszjasiuk @macieksawicki

**Comment by mateuszjasiuk** [comment]
i think we should either use HAML( most popular ) or slim http://slim-lang.com/ which works faster and is faster to write (http://graffzon.tumblr.com/post/15303347654/comparsion-of-haml-slim-erb)

**Comment by puradawid** [comment]
Lets stay with HAML.
